name: Generate Datas

on:
  schedule: # execute every 12 hours
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
      # Check out the repository
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Generate Snake Animation
      - name: Generate Snake Animation
        uses: Platane/snk@v2
        with:
          github_user_name: Vicckyx
          
      # Deploy the SVG to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
